"""End-to-end tests for HeyGen provider.

These tests make actual API calls to the HeyGen service.
Requires environment variables:
  - HEYGEN_API_KEY: HeyGen API key
  - HEYGEN_AVATAR_ID: Avatar ID to use for generation
  - HEYGEN_VOICE_ID: Voice ID to use for generation

Run with: uv run pytest tests/e2e/test_heygen.py -v -m e2e
Skip with: uv run pytest tests/e2e/test_heygen.py -v -m "not e2e"
"""

import os

import pytest

from tarash.tarash_gateway import api
from tarash.tarash_gateway.models import (
    VideoGenerationConfig,
    VideoGenerationRequest,
    VideoGenerationResponse,
    VideoGenerationUpdate,
)

# ==================== Fixtures ====================


@pytest.fixture(scope="module")
def heygen_api_key():
    """Get HeyGen API key from environment."""
    api_key = os.getenv("HEYGEN_API_KEY")
    if not api_key:
        pytest.skip("HEYGEN_API_KEY environment variable not set")
    return api_key


@pytest.fixture(scope="module")
def heygen_avatar_id():
    """Get HeyGen avatar ID from environment."""
    avatar_id = os.getenv("HEYGEN_AVATAR_ID")
    if not avatar_id:
        pytest.skip("HEYGEN_AVATAR_ID environment variable not set")
    return avatar_id


@pytest.fixture(scope="module")
def heygen_voice_id():
    """Get HeyGen voice ID from environment."""
    voice_id = os.getenv("HEYGEN_VOICE_ID")
    if not voice_id:
        pytest.skip("HEYGEN_VOICE_ID environment variable not set")
    return voice_id


@pytest.fixture(scope="module")
def heygen_config(heygen_api_key, heygen_avatar_id, heygen_voice_id):
    """Create a base HeyGen config with avatar/voice from environment."""
    return VideoGenerationConfig(
        model="heygen/avatar-v2",
        provider="heygen",
        api_key=heygen_api_key,
        timeout=600,
        max_poll_attempts=120,
        poll_interval=5,
        provider_config={
            "avatar_id": heygen_avatar_id,
            "voice_id": heygen_voice_id,
        },
    )


# ==================== E2E Tests ====================


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_avatar_video_async(heygen_config):
    """
    Test async avatar video generation with progress tracking.

    Covers: async path, 1:1 aspect ratio, progress callback,
    full response validation (request_id, raw_response, status sequence).
    """
    progress_updates: list[VideoGenerationUpdate] = []

    async def progress_callback(update: VideoGenerationUpdate) -> None:
        progress_updates.append(update)
        print(f"  Progress: {update.status}")

    request = VideoGenerationRequest(
        prompt="Hello! This is a test video generated by the Tarash gateway. Thank you.",
        aspect_ratio="1:1",
    )

    print("\nGenerating HeyGen avatar video (async, 1:1)")
    response = await api.generate_video_async(
        heygen_config, request, on_progress=progress_callback
    )

    assert isinstance(response, VideoGenerationResponse)
    assert response.request_id is not None
    assert response.status == "completed"
    assert isinstance(response.raw_response, dict)
    assert isinstance(response.video, str), "Video should be a string URL"
    assert response.video.startswith("http"), (
        f"Expected HTTP URL, got: {response.video}"
    )
    assert len(progress_updates) > 0, "Expected at least one progress update"
    statuses = [u.status for u in progress_updates]
    assert "completed" in statuses, "Expected 'completed' status in progress updates"

    print(f"  Request ID: {response.request_id}")
    print(f"  Video URL:  {response.video}")
    print(f"  Duration:   {response.duration}s")
    print(f"  Progress updates: {len(progress_updates)}")


@pytest.mark.e2e
def test_avatar_video_sync(heygen_config):
    """
    Test sync avatar video generation.

    Covers: sync path, 1:1 aspect ratio.
    """
    request = VideoGenerationRequest(
        prompt="Hello from the Tarash gateway sync test!",
        aspect_ratio="1:1",
    )

    print("\nGenerating HeyGen avatar video (sync, 1:1)")
    response = api.generate_video(heygen_config, request)

    assert isinstance(response, VideoGenerationResponse)
    assert response.request_id is not None
    assert response.status == "completed"
    assert isinstance(response.video, str), "Video should be a string URL"
    assert response.video.startswith("http"), (
        f"Expected HTTP URL, got: {response.video}"
    )

    print(f"  Request ID: {response.request_id}")
    print(f"  Video URL:  {response.video}")


@pytest.mark.e2e
@pytest.mark.asyncio
async def test_avatar_video_extra_params(
    heygen_api_key, heygen_avatar_id, heygen_voice_id
):
    """
    Test extra_params behavior: avatar_id/voice_id override provider_config defaults,
    and styling params (avatar_style, voice_speed, voice_emotion, caption) are applied.

    Covers: 1:1 aspect ratio, override priority, avatar_style, voice_speed,
    voice_emotion, caption.
    """
    config = VideoGenerationConfig(
        model="heygen/avatar-v2",
        provider="heygen",
        api_key=heygen_api_key,
        timeout=600,
        max_poll_attempts=120,
        poll_interval=5,
        provider_config={
            "avatar_id": "placeholder-avatar",
            "voice_id": "placeholder-voice",
        },
    )

    request = VideoGenerationRequest(
        prompt="Welcome to our platform! We are excited to have you here today.",
        aspect_ratio="1:1",
        extra_params={
            "avatar_id": heygen_avatar_id,
            "voice_id": heygen_voice_id,
            "avatar_style": "normal",
            "voice_speed": 1.1,
            "voice_emotion": "Friendly",
            "caption": True,
        },
    )

    print(
        "\nGenerating HeyGen avatar video (async, 1:1, extra_params override + custom params)"
    )
    response = await api.generate_video_async(config, request)

    assert isinstance(response, VideoGenerationResponse)
    assert response.status == "completed"
    assert isinstance(response.video, str), "Video should be a string URL"
    assert response.video.startswith("http"), (
        f"Expected HTTP URL, got: {response.video}"
    )

    print(f"  Request ID: {response.request_id}")
    print(f"  Video URL:  {response.video}")
