"""Tarash Gateway - Unified interface for AI generation models."""

import importlib.metadata

try:
    __version__ = importlib.metadata.version("tarash-gateway")
except importlib.metadata.PackageNotFoundError:
    __version__ = "0.1.0"

from .api import (
    generate_image,
    generate_image_async,
    generate_image_batch,
    generate_image_batch_async,
    generate_sts,
    generate_sts_async,
    generate_sts_batch,
    generate_sts_batch_async,
    generate_tts,
    generate_tts_async,
    generate_tts_batch,
    generate_tts_batch_async,
    generate_video,
    generate_video_async,
    generate_video_batch,
    generate_video_batch_async,
    get_provider_field_mapping,
    register_provider,
    register_provider_field_mapping,
)
from .exceptions import (
    ContentModerationError,
    GenerationFailedError,
    HTTPConnectionError,
    HTTPError,
    TarashException,
    TimeoutError,
    ValidationError,
)
from .models import (
    AspectRatio,
    AudioGenerationConfig,
    AudioOutputFormat,
    BatchCompletionUpdate,
    BatchItem,
    BatchItemResult,
    BatchResponse,
    ImageBatchCompletionUpdate,
    ImageBatchItem,
    ImageBatchItemResult,
    ImageBatchResponse,
    ImageGenerationConfig,
    ImageGenerationRequest,
    ImageGenerationResponse,
    ImageType,
    Resolution,
    STSBatchCompletionUpdate,
    STSBatchItem,
    STSBatchItemResult,
    STSBatchResponse,
    STSRequest,
    STSResponse,
    STSUpdate,
    TTSBatchCompletionUpdate,
    TTSBatchItem,
    TTSBatchItemResult,
    TTSBatchResponse,
    TTSRequest,
    TTSResponse,
    TTSUpdate,
    VideoBatchCompletionUpdate,
    VideoBatchItem,
    VideoBatchItemResult,
    VideoBatchResponse,
    VideoGenerationConfig,
    VideoGenerationRequest,
    VideoGenerationResponse,
    VideoGenerationUpdate,
    format_to_content_type,
)

__all__ = [
    # API functions
    "generate_video",
    "generate_video_async",
    "generate_image",
    "generate_image_async",
    "generate_tts",
    "generate_tts_async",
    "generate_sts",
    "generate_sts_async",
    "register_provider",
    "register_provider_field_mapping",
    "get_provider_field_mapping",
    # Batch API functions
    "generate_video_batch",
    "generate_video_batch_async",
    "generate_image_batch",
    "generate_image_batch_async",
    "generate_tts_batch",
    "generate_tts_batch_async",
    "generate_sts_batch",
    "generate_sts_batch_async",
    # Models
    "VideoGenerationConfig",
    "VideoGenerationRequest",
    "VideoGenerationResponse",
    "VideoGenerationUpdate",
    "ImageGenerationConfig",
    "ImageGenerationRequest",
    "ImageGenerationResponse",
    "AudioGenerationConfig",
    "TTSRequest",
    "TTSResponse",
    "TTSUpdate",
    "STSRequest",
    "STSResponse",
    "STSUpdate",
    # Batch Models (generic)
    "BatchItem",
    "BatchItemResult",
    "BatchResponse",
    "BatchCompletionUpdate",
    # Batch Models (video)
    "VideoBatchItem",
    "VideoBatchItemResult",
    "VideoBatchResponse",
    "VideoBatchCompletionUpdate",
    # Batch Models (image)
    "ImageBatchItem",
    "ImageBatchItemResult",
    "ImageBatchResponse",
    "ImageBatchCompletionUpdate",
    # Batch Models (TTS)
    "TTSBatchItem",
    "TTSBatchItemResult",
    "TTSBatchResponse",
    "TTSBatchCompletionUpdate",
    # Batch Models (STS)
    "STSBatchItem",
    "STSBatchItemResult",
    "STSBatchResponse",
    "STSBatchCompletionUpdate",
    # Types
    "Resolution",
    "AspectRatio",
    "ImageType",
    "AudioOutputFormat",
    "format_to_content_type",
    # Exceptions
    "TarashException",
    "ValidationError",
    "ContentModerationError",
    "HTTPError",
    "HTTPConnectionError",
    "TimeoutError",
    "GenerationFailedError",
]
